### ISSUE TITLE
Error with AC180

### ISSUE THREAD

**Issue by jsaiko** [ftrueck/bluetti_mqtt#1]
Hello.  I cant seem to get past this error when attempting to connect to my AC180.  The android app picks it up fine.

2024-06-14 14:41:04 INFO     Connecting to MQTT broker...
2024-06-14 14:41:04 INFO     Starting to poll clients...
2024-06-14 14:41:04 INFO     Connecting to clients: ['C9:9C:3C:7B:C7:80']
2024-06-14 14:41:05 INFO     Connected to MQTT broker
2024-06-14 14:41:10 INFO     Connected to device: C9:9C:3C:7B:C7:80
2024-06-14 14:41:10 INFO     Device C9:9C:3C:7B:C7:80 has name: AC1802411002689394
2024-06-14 14:41:10 WARNING  Delayed reconnect to C9:9C:3C:7B:C7:80 after error
2024-06-14 14:41:16 INFO     Connected to device: C9:9C:3C:7B:C7:80
2024-06-14 14:41:16 WARNING  Delayed reconnect to C9:9C:3C:7B:C7:80 after error
2024-06-14 14:41:16 ERROR    Crashing with uncaught exception:
Traceback (most recent call last):
  File "/opt/bluetti-mqtt/lib/python3.11/site-packages/bluetti_mqtt/device_handler.py", line 31, in run
    await asyncio.gather(*(polling_tasks + pack_polling_tasks + [manager_task]))
  File "/opt/bluetti-mqtt/lib/python3.11/site-packages/bluetti_mqtt/device_handler.py", line 50, in _poll
    await self._poll_with_command(device, command)
  File "/opt/bluetti-mqtt/lib/python3.11/site-packages/bluetti_mqtt/device_handler.py", line 89, in _poll_with_command
    response = cast(bytes, await response_future)
                           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bluetti-mqtt/lib/python3.11/site-packages/bluetti_mqtt/bluetooth/client.py", line 119, in _perform_command
    await self.client.write_gatt_char(
  File "/opt/bluetti-mqtt/lib/python3.11/site-packages/bleak/__init__.py", line 786, in write_gatt_char
    await self._backend.write_gatt_char(characteristic, data, response)
  File "/opt/bluetti-mqtt/lib/python3.11/site-packages/bleak/backends/bluezdbus/client.py", line 835, in write_gatt_char
    reply = await self._bus.call(
            ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bluetti-mqtt/lib/python3.11/site-packages/dbus_fast/aio/message_bus.py", line 385, in call
    await future
  File "src/dbus_fast/aio/message_reader.py", line 19, in dbus_fast.aio.message_reader._message_reader
  File "src/dbus_fast/_private/unmarshaller.py", line 777, in dbus_fast._private.unmarshaller.Unmarshaller._unmarshall
  File "src/dbus_fast/_private/unmarshaller.py", line 638, in dbus_fast._private.unmarshaller.Unmarshaller._read_header
  File "src/dbus_fast/_private/unmarshaller.py", line 374, in dbus_fast._private.unmarshaller.Unmarshaller._read_to_pos
  File "src/dbus_fast/_private/unmarshaller.py", line 317, in dbus_fast._private.unmarshaller.Unmarshaller._read_sock_with_fds
EOFError
2024-06-14 14:41:16 INFO     Shutting down...

**Comment by jsaiko** [comment]
related to https://github.com/Patrick762/hassio-bluetti-bt/issues/120

**Comment by ftrueck** [comment]
True, seems to be a problem that has to be solved. 
Unfortunately I am not into the process of reverse engineering.
So I am not able to fix this for now. If a solution is found I can try to implement it but until then I have to leave the issue open.

**Comment by tackarama** [comment]
I have an EP500Pro which works fine and AC180 that doesn't as expected from previous posts.

Any help would be gratefully received & I'm happy to test  if that helps.

**Comment by voltagex** [comment]
I have an AC180.

I can confirm that

```
ARM v2074.06
DSP v2078.06
BSP v1033.08
```

does *not* have encryption, or works with this fork.

@tackarama what is your app version and component versions like above?

I am not being offered any firmware updates via iOS app version 2.3.13.

**Comment by jsaiko** [comment]
There is a fork which has the encryption working here:

https://github.com/nhurman/bluetti_mqtt/commit/bf037c35c328af8807b60b3ed109e21b23e3d503
